#!/usr/bin/env bash
set -e

# ==========================================
# Parasyte Installer Script
# Usage: curl -fsSL https://raw.githubusercontent.com/Shiyinq/parasyte/main/install.sh | bash
# ==========================================

REPO="Shiyinq/parasyte"
INSTALL_DIR="/usr/local/lib/parasyte"
BIN_DIR="/usr/local/bin"
BIN_NAME="parasyte"

# --- Colors ---
GREEN='\033[0;32m'
BOLD='\033[1m'
NC='\033[0m'

echo -e "${GREEN}${BOLD}"
cat << "EOF"
 ▄  ▄▄▄▄▄▄    ▄▄▄▄▄▄    ▄  ▄▄▄▄▄▄     ▄▄▄▄▄▄        ▄▄▄▄▄  ▐█▌▌   ▐██▌    ▄▄▄▄▄▄▄▄    ▄▄▄▄▄▄        
 ▐█▌▀  ▀▀█▄ ▄▄█▀  ▀▀█▄  ▐█▌▀  ▀▀█▄  ▄▄█▀  ▀▀█▄    ▄▄▀ ▀▀█▀ ▐█▌▌   ▐██▌ ▄▄█▀ ██  ▀█▄ ▄▄█▀  ▀▀█▄      
 ▐██▌  ▄▄█▌ ▐█▌    ▐▐█▌ ▐██▌   ▄█▌  ▐█▌    ▐▐█▌   ██▄▄     ▐██▄▄  ▐██▌  █▀ ▐▐█▌     ▐█▌    ▐▐█▌     
 ▐██▌▀▀▀▀▀  ▐█▌▀▀▀▀▀██▌ ▐██▌▀▀▀▄▄▄  ▐█▌▀▀▀▀▀██▌   ▀▀▀████▄  ▀▀▀▀▀▀▀██▌      ▐██     ▐██▀▀▀▀         
  ▐█▌       ▐█▌    ▐██▌  ▐█▌    ██▌ ▐█▌    ▐██▌ ▄▄     ▀▀█ ▐█▌    ▐██▌      ▐██▌     ▐█▌▄▄▄▄▄       
   ▀         ▀      ▀▀    ▀      ▀   ▀      ▀▀   ▀▀▀▀▀▀▀    ▀      ▀▀        ▀        ▀▀▀▀▀         
EOF
echo -e "${NC}"
echo "Preparing to install Parasyte (Polyglot Tool) from GitHub..."

# --- Detect OS ---
OS="$(uname -s)"
if [ "$OS" = "Darwin" ]; then
    ASSET_SUFFIX="macos-latest.tar.gz"
elif [ "$OS" = "Linux" ]; then
    ASSET_SUFFIX="ubuntu-latest.tar.gz"
else
    echo "❌ Unsupported OS: $OS. Windows users should download the .zip release manually."
    exit 1
fi

echo "=> Detecting latest release for $OS..."

# Fetch the latest release version from GitHub API
LATEST_TAG=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

if [ -z "$LATEST_TAG" ]; then
    echo "❌ Error: Could not fetch the latest release from GitHub."
    echo "Have you created a Release on GitHub yet?"
    exit 1
fi

DOWNLOAD_URL="https://github.com/$REPO/releases/download/$LATEST_TAG/parasyte-$ASSET_SUFFIX"
TMP_DIR=$(mktemp -d)
TAR_FILE="$TMP_DIR/parasyte.tar.gz"

echo "=> Downloading Parasyte $LATEST_TAG from GitHub Releases..."
# Download the tar.gz file from GitHub Release
curl -# -L -o "$TAR_FILE" "$DOWNLOAD_URL"

echo "=> Extracting to $INSTALL_DIR (This requires sudo permissions)..."
sudo rm -rf "$INSTALL_DIR"
sudo mkdir -p "$INSTALL_DIR"
# Extract the parasyte.dist folder directly to /usr/local/lib
sudo tar -xzf "$TAR_FILE" -C "$INSTALL_DIR" --strip-components=1

echo "=> Creating symlink in $BIN_DIR..."
# Note: We use 'parasyte.bin' as generated by Nuitka on Mac/Linux
sudo ln -sf "$INSTALL_DIR/parasyte.bin" "$BIN_DIR/$BIN_NAME"

# Clean up temporary files
rm -rf "$TMP_DIR"

echo ""
echo -e "${GREEN}✅ Parasyte installed successfully!${NC}"
echo -e "You can now type ${BOLD}parasyte${NC} from anywhere in your terminal."
